/*
 * ErrorTypes.h
 *
 *  Created on: Oct 9, 2024
 *      Author: khadeejaabbas, millaine
 */

#ifndef INC_TASK_H_FILES_ERRORTYPES_H_
#define INC_TASK_H_FILES_ERRORTYPES_H_

#pragma once

// make enum for trips from excel sheet
typedef enum
{
    OVERTEMP_TRIP,
    HIGHCELLVOLTAGE_TRIP,
	LOWCELLVOLTAGE_TRIP,
	COMMONHIGHCURRENT_TRIP,
	MOTORHIGHCURRENT_TRIP,
	ARRAYHIGHCURRENT_TRIP,
	LVHIGHCURRENT_TRIP,
	CHARGEHIGHCURRENT_TRIP,
    PROTECTION_TRIP,
	ORIONMESSAGETIMEOUT_TRIP,
	CONTACTORDISCONNECTED_TRIP,
	CONTACTORCONNECTED_TRIP,
	HIGHBATTERY_TRIP,
	COMMONHEARTBEATDEAD_TRIP,
	MOTOR1HEARTBEATDEAD_TRIP,
	MOTOR2HEARTBEATDEAD_TRIP,
	ARRAYHEARTBEATDEAD_TRIP,
	LVHEARTBEATDEAD_TRIP,
	CHARGEHEARTBEATDEAD_TRIP
} ErrorCodes;


#endif /* INC_TASK_H_FILES_ERRORTYPES_H_ */
